In [1]:
# Import library
import re
import nltk
import time
import string
import itertools
import collections
import numpy as np
import pandas as pd
from sklearn import svm
from sklearn.svm import SVC
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [2]:
reviews_df = pd.read_csv("data/hasil-preprocessing-data.csv")
reviews_df.head(10)

Unnamed: 0                                           stopword sentiment
0           0                                              mudah  positive
1           1  aplikasi bantu karna daerah mksih yahh aplikas...  positive
2           2                                        bagus sehat  positive
3           3  tombol tuju nya gak aplikasi user friendly ban...  positive
4           4                                              mudah  positive
5           5  selamat malam aplikasi nya bagus manfaat aplik...  positive
6           6                           puas aflikasi ecek orang  positive
7           7  aplikasi bantu karna daerah mksih yahh aplikas...  positive
8           8                bantu cepat layan jamin sehat klien  positive
9           9                      aplikasi pantau kembang covid  positive

In [3]:
reviews_df = reviews_df.dropna()
reviews_df.head(10)

Unnamed: 0                                           stopword sentiment
0           0                                              mudah  positive
1           1  aplikasi bantu karna daerah mksih yahh aplikas...  positive
2           2                                        bagus sehat  positive
3           3  tombol tuju nya gak aplikasi user friendly ban...  positive
4           4                                              mudah  positive
5           5  selamat malam aplikasi nya bagus manfaat aplik...  positive
6           6                           puas aflikasi ecek orang  positive
7           7  aplikasi bantu karna daerah mksih yahh aplikas...  positive
8           8                bantu cepat layan jamin sehat klien  positive
9           9                      aplikasi pantau kembang covid  positive

In [4]:
reviews_df.head(10)

Unnamed: 0                                           stopword sentiment
0           0                                              mudah  positive
1           1  aplikasi bantu karna daerah mksih yahh aplikas...  positive
2           2                                        bagus sehat  positive
3           3  tombol tuju nya gak aplikasi user friendly ban...  positive
4           4                                              mudah  positive
5           5  selamat malam aplikasi nya bagus manfaat aplik...  positive
6           6                           puas aflikasi ecek orang  positive
7           7  aplikasi bantu karna daerah mksih yahh aplikas...  positive
8           8                bantu cepat layan jamin sehat klien  positive
9           9                      aplikasi pantau kembang covid  positive

In [5]:
tfidf_vectorizer = TfidfVectorizer()
tfidf_transformer = tfidf_vectorizer.fit(reviews_df['stopword'].values.astype('U'))
tfidf_vectors = tfidf_transformer.transform(reviews_df['stopword'].values.astype('U'))

In [6]:
df_tfidf = pd.DataFrame(tfidf_vectors.toarray(), columns=tfidf_vectorizer.get_feature_names())
df_tfidf

C:\Users\Admin\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


aada  aamiin  aaneh  abal  abalabal  abis  absen  acara  accept  ace  \
0      0.0     0.0    0.0   0.0       0.0   0.0    0.0    0.0     0.0  0.0   
1      0.0     0.0    0.0   0.0       0.0   0.0    0.0    0.0     0.0  0.0   
2      0.0     0.0    0.0   0.0       0.0   0.0    0.0    0.0     0.0  0.0   
3      0.0     0.0    0.0   0.0       0.0   0.0    0.0    0.0     0.0  0.0   
4      0.0     0.0    0.0   0.0       0.0   0.0    0.0    0.0     0.0  0.0   
...    ...     ...    ...   ...       ...   ...    ...    ...     ...  ...   
2481   0.0     0.0    0.0   0.0       0.0   0.0    0.0    0.0     0.0  0.0   
2482   0.0     0.0    0.0   0.0       0.0   0.0    0.0    0.0     0.0  0.0   
2483   0.0     0.0    0.0   0.0       0.0   0.0    0.0    0.0     0.0  0.0   
2484   0.0     0.0    0.0   0.0       0.0   0.0    0.0    0.0     0.0  0.0   
2485   0.0     0.0    0.0   0.0       0.0   0.0    0.0    0.0     0.0  0.0   

      ...  ykin  ymn  yng   yo  you  yuk  zebra  zikir  zona  zonk  
0     ...   0.0  0.0  0.0  0.0  0.0  0.0    0.0    0.0   0.0   0.0  
1     ...   0.0  0.0  0.0  0.0  0.0  0.0    0.0    0.0   0.0   0.0  
2     ...   0.0  0.0  0.0  0.0  0.0  0.0    0.0    0.0   0.0   0.0  
3     ...   0.0  0.0  0.0  0.0  0.0  0.0    0.0    0.0   0.0   0.0  
4     ...   0.0  0.0  0.0  0.0  0.0  0.0    0.0    0.0   0.0   0.0  
...   ...   ...  ...  ...  ...  ...  ...    ...    ...   ...   ...  
2481  ...   0.0  0.0  0.0  0.0  0.0  0.0    0.0    0.0   0.0   0.0  
2482  ...   0.0  0.0  0.0  0.0  0.0  0.0    0.0    0.0   0.0   0.0  
2483  ...   0.0  0.0  0.0  0.0  0.0  0.0    0.0    0.0   0.0   0.0  
2484  ...   0.0  0.0  0.0  0.0  0.0  0.0    0.0    0.0   0.0   0.0  
2485  ...   0.0  0.0  0.0  0.0  0.0  0.0    0.0    0.0   0.0   0.0  

[2486 rows x 3559 columns]

In [7]:
X = df_tfidf.values
y = reviews_df['sentiment'].values
# num_data, num_features = X.shape

print(X)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [8]:
copy_reviews_df = reviews_df.copy(deep=True)

In [9]:
copy_reviews_df['ls'] = copy_reviews_df['stopword'].apply(lambda x: x.split(" "))
copy_reviews_df.head()

Unnamed: 0                                           stopword sentiment  \
0           0                                              mudah  positive   
1           1  aplikasi bantu karna daerah mksih yahh aplikas...  positive   
2           2                                        bagus sehat  positive   
3           3  tombol tuju nya gak aplikasi user friendly ban...  positive   
4           4                                              mudah  positive   

                                                  ls  
0                                            [mudah]  
1  [aplikasi, bantu, karna, daerah, mksih, yahh, ...  
2                                     [bagus, sehat]  
3  [tombol, tuju, nya, gak, aplikasi, user, frien...  
4                                            [mudah]

In [10]:
# positive reviews
positive_reviews = copy_reviews_df[copy_reviews_df['sentiment']=='positive']['ls']
print("Total positive reviews: ", len(positive_reviews))
df_positive_document = pd.DataFrame(positive_reviews)
positive_reviews_words = list(itertools.chain(*positive_reviews))
print("Total words in positive reviews:", len(positive_reviews_words))

# negative reviews
negative_reviews = copy_reviews_df[copy_reviews_df['sentiment']=='negative']['ls']
print("Total negative reviews: ", len(negative_reviews))
df_negative_document = pd.DataFrame(negative_reviews)
negative_reviews_words = list(itertools.chain(*negative_reviews))
print("Total words in negative reviews:", len(negative_reviews_words))

Total positive reviews:  582
Total words in positive reviews: 3450
Total negative reviews:  1904
Total words in negative reviews: 19720


In [11]:
# convert list formated string to list
import ast

def convert_text_list(texts):
    texts = ast.literal_eval(str(texts))
    return [text for text in texts]

df_positive_document["comment_list"] = df_positive_document['ls'].apply(convert_text_list)
df_negative_document["comment_list"] = df_negative_document['ls'].apply(convert_text_list)

In [12]:
def calc_TF(document):
    # Counts the number of times the word appears in review
    TF_dict = {}
    for term in document:
        if term in TF_dict:
            TF_dict[term] += 1
        else:
            TF_dict[term] = 1
    # Computes tf for each word
    for term in TF_dict:
        TF_dict[term] = TF_dict[term] / len(document)
    return TF_dict

df_positive_document["TF_dict"] = df_positive_document['comment_list'].apply(calc_TF)
df_negative_document["TF_dict"] = df_negative_document['comment_list'].apply(calc_TF)

# df_positive_document["TF_dict"].head()
# df_negative_document["TF_dict"].head()

In [14]:
def calc_DF(tfDict):
    count_DF = {}
    # Run through each document's tf dictionary and increment countDict's (term, doc) pair
    for document in tfDict:
        for term in document:
            if term in count_DF:
                count_DF[term] += 1
            else:
                count_DF[term] = 1
    return count_DF

DF_positive = calc_DF(df_positive_document["TF_dict"])
DF_negative = calc_DF(df_negative_document["TF_dict"])

print(DF_positive)
print(len(DF_positive))
print(len(DF_negative))

{'mudah': 76, 'aplikasi': 150, 'bantu': 158, 'karna': 7, 'daerah': 2, 'mksih': 2, 'yahh': 2, 'pedulilindung': 3, 'bagus': 124, 'sehat': 34, 'tombol': 1, 'tuju': 8, 'nya': 44, 'gak': 11, 'user': 2, 'friendly': 2, 'banget': 19, 'bukti': 2, 'hebat': 3, 'kembang': 5, 'ilmu': 1, 'teknologi': 1, 'alami': 3, 'tingkat': 6, 'syaloom': 1, 'selamat': 6, 'malam': 1, 'manfaat': 51, 'wnitapi': 1, 'kurg': 1, 'lengkaphanya': 1, 'pinta': 1, 'nik': 6, 'ktp': 3, 'ajaknpa': 1, 'tambahahin': 1, 'no': 2, 'pasport': 1, 'mendaftarbagaimna': 1, 'dg': 3, 'warga': 8, 'negara': 4, 'indonesia': 21, 'vaksin': 73, 'bagaimna': 1, 'daftar': 4, 'peduli': 32, 'lindung': 34, 'terimakasih': 21, 'puas': 6, 'aflikasi': 2, 'ecek': 3, 'orang': 8, 'cepat': 19, 'layan': 12, 'jamin': 1, 'klien': 1, 'pantau': 1, 'covid': 30, 'udah': 14, 'ubah': 2, 'nama': 2, 'sertifikat': 33, 'hurup': 1, 'kapital': 1, 'gimana': 1, 'ya': 14, 'tlong': 1, 'terima': 32, 'kasih': 43, 'sayang': 1, 'akses': 17, 'data': 12, 'orangkeluarga': 1, 'mohon': 5

In [134]:
# words frequency

positive_words_frequency = collections.Counter(DF_positive)
negative_words_frequency = collections.Counter(DF_negative)

positive_freq_words_df = pd.DataFrame.from_records(list(dict(positive_words_frequency).items()), columns=['word','frequency'])
negative_freq_words_df = pd.DataFrame.from_records(list(dict(negative_words_frequency).items()), columns=['word','frequency'])
positive_freq_words_df

word  frequency
0            mudah         76
1         aplikasi        150
2            bantu        158
3            karna          7
4           daerah          2
..             ...        ...
979        mumpung          1
980       prebayar          1
981  memebantubuat          1
982       keprluan          1
983        koneksi          1

[984 rows x 2 columns]

In [135]:
df_count_words = pd.concat([positive_freq_words_df, negative_freq_words_df], axis = 1)

df_count_words.drop(['word'], axis=1, inplace=True)
df_count_words.columns = ['positive', 'negative']
df_count_words['positive'] = df_count_words['positive'].fillna(0)
df_count_words['negative'] = df_count_words['negative'].fillna(0)
df_count_words['positive'] = pd.to_numeric(df_count_words['positive'], downcast='integer')
df_count_words['negative'] = pd.to_numeric(df_count_words['negative'], downcast='integer')
df_count_words

positive  negative
0           76       295
1          150         4
2          158       685
3            7       183
4            2       107
...        ...       ...
3099         0         1
3100         0         1
3101         0         1
3102         0         1
3103         0         1

[3104 rows x 2 columns]

In [136]:
num_features = len(df_count_words)
num_features

3104

In [137]:
df_count_positif = reviews_df[reviews_df["sentiment"] == "positive"]
df_count_negatif = reviews_df[reviews_df["sentiment"] == "negative"]
print("positive: ", len(df_count_positif))
print("negative: ", len(df_count_negatif))

positive:  582
negative:  1904


In [138]:
df_count_words

positive  negative
0           76       295
1          150         4
2          158       685
3            7       183
4            2       107
...        ...       ...
3099         0         1
3100         0         1
3101         0         1
3102         0         1
3103         0         1

[3104 rows x 2 columns]

In [139]:
print(df_count_words.iloc[20,1])

2


In [140]:
n_positif = len(df_count_positif)
n_negatif = len(df_count_negatif)

# mendefinisikan fungsi unyuk menghitung pf, qf, dan qer score
def calculate_pf(df_positif, n_positif):
    pf = (df_positif + 0.5) / (n_positif + 1)
    return pf

def calculate_qf(df_negatif, n_negatif):
    qf = (df_negatif + 0.5) / (n_negatif + 0.5)
    return qf

def score_qer(pf, qf):
    score = np.abs(pf+qf) / np.abs(pf-qf)
    return score

# melakukan perhitungan score qer untuk masing masing feature

score = np.zeros((num_features, 2))


for i in range(num_features):
    df_positif = df_count_words.iloc[i, 0]
    pf = calculate_pf(df_positif, n_positif)
    df_negatif = df_count_words.iloc[i, 1]
    qf = calculate_qf(df_negatif, n_negatif)
    score_qr = score_qer(pf, qf)

    score[i, 0] = i
    score[i, 1] = score_qr
    
# menyimpan hasil perhitungan qer score ke dalam dataframe
df_qer = pd.DataFrame(score, columns=["index", "qer_score"])
df_qer = df_qer.astype({'index':'int'})
df_qer

index  qer_score
0         0  11.961770
1         1   1.018475
2         2   7.174130
3         3   1.308182
4         4   1.164433
...     ...        ...
3099   3099  23.495177
3100   3100  23.495177
3101   3101  23.495177
3102   3102  23.495177
3103   3103  23.495177

[3104 rows x 2 columns]

In [141]:
# melihat isi dataframe df_qer yang sudah diurutkan nilai qer dari terbesar ke terendah
print(df_qer.sort_values(by='qer_score', ascending=False))

     index   qer_score
266    266  345.038710
52      52  206.874799
53      53   71.822884
143    143   50.021879
373    373   50.021879
..     ...         ...
43      43    1.038200
68      68    1.028662
126    126    1.022597
26      26    1.021185
1        1    1.018475

[3104 rows x 2 columns]


In [142]:
# ratio feature selection

def ratio_feature(percent, num_features):
    result = int((percent/100) * num_features)
    return result

twenty_five_percent = ratio_feature(25, num_features)
fifty_percent = ratio_feature(50, num_features)
seventy_five_percent = ratio_feature(75, num_features)
one_hundred_percent = ratio_feature(100, num_features)
print(one_hundred_percent)

3104


In [143]:
# fungsi untuk menghitung akurasi, metrics, report qer

def qer_accuracy(df_qer, num_feature_used, df_tfidf, y):
    df_sorted_qer = df_qer.sort_values(by='qer_score', ascending=False).head(num_feature_used)
    idx_word = df_sorted_qer['index'].values
    X_fix = df_tfidf.iloc[:, list(idx_word)]
    
    X_train, X_test, y_train, y_test = train_test_split(X_fix, y, test_size=0.2, random_state=1)

    linear_svm=SVC(kernel='linear') 
    linear_svm.fit(X_train, y_train)
    predicted = linear_svm.predict(X_test)
    
#     for i in range(len(X_test)):
#         res=linear_svc.predict(X_test)[i]
#         if res=="positive":
#             print("positif")
#         elif res=="negative":
#             print("negatif")
    
#     y_pred_train = linear_svc.predict(X_train)
#     print('Training-set accuracy score: {0:0.4f}'. format(accuracy_score(y_train, y_pred_train)))
    print('Akurasi = %s ' %accuracy_score(y_test, predicted))
#     print('Presisi = %s ' %precision_score(y_test, predicted, average="binary", pos_label='negative'))
#     print('Recall = %s ' %recall_score(y_test, predicted, average="binary", pos_label='negative'))
#     print('F-measure = %s ' %f1_score(y_test, predicted, average="binary", pos_label='negative'))

In [144]:
start = time.process_time()
qer_accuracy(df_qer, twenty_five_percent, df_tfidf, y)
print(time.process_time() - start)

Akurasi = 0.8012048192771084 
1.359375


In [145]:
start = time.process_time()
qer_accuracy(df_qer, fifty_percent, df_tfidf, y)
print(time.process_time() - start)

Akurasi = 0.8273092369477911 
2.703125


In [146]:
start = time.process_time()
qer_accuracy(df_qer, seventy_five_percent, df_tfidf, y)
print(time.process_time() - start)

Akurasi = 0.891566265060241 
3.828125


In [147]:
start = time.process_time()
qer_accuracy(df_qer, one_hundred_percent, df_tfidf, y)    
print(time.process_time() - start)

Akurasi = 0.9317269076305221 
4.375


In [148]:
def svm_linier(df_tfidf, y):
    
    X_train, X_test, y_train, y_test = train_test_split(df_tfidf, y, test_size=0.2, random_state=1)
    
    linear_svm=SVC(kernel='linear') 
    linear_svm.fit(X_train, y_train)
    predicted = linear_svm.predict(X_test)
    
#     for i in range(len(X_test)):
#         res=linear_svc.predict(X_test)[i]
#         if res=="positive":
#             print("positif")
#         elif res=="negative":
#             print("negatif")
    
#     y_pred_train = linear_svc.predict(X_train)
#     print('Training-set accuracy score: {0:0.4f}'. format(accuracy_score(y_train, y_pred_train)))
    print('Akurasi = %s ' %accuracy_score(y_test, predicted))
#     print('Presisi = %s ' %precision_score(y_test, predicted, average="binary", pos_label='negative'))
#     print('Recall = %s ' %recall_score(y_test, predicted, average="binary", pos_label='negative'))
#     print('F-measure = %s ' %f1_score(y_test, predicted, average="binary", pos_label='negative'))


In [149]:
start = time.process_time()
svm_linier(df_tfidf, y)    
print(time.process_time() - start)

Akurasi = 0.929718875502008 
5.0625
